/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShowerRouteImport } from './routes/shower'
import { Route as SaunaRouteImport } from './routes/sauna'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlungeRouteImport } from './routes/plunge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SensorsIndexRouteImport } from './routes/sensors.index'
import { Route as SensorsSaunaRouteImport } from './routes/sensors.sauna'
import { Route as SensorsPlungeRouteImport } from './routes/sensors.plunge'
import { Route as SensorsBundleRouteImport } from './routes/sensors.bundle'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowerRoute = ShowerRouteImport.update({
  id: '/shower',
  path: '/shower',
  getParentRoute: () => rootRouteImport,
} as any)
const SaunaRoute = SaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlungeRoute = PlungeRouteImport.update({
  id: '/plunge',
  path: '/plunge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsIndexRoute = SensorsIndexRouteImport.update({
  id: '/sensors/',
  path: '/sensors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsSaunaRoute = SensorsSaunaRouteImport.update({
  id: '/sensors/sauna',
  path: '/sensors/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsPlungeRoute = SensorsPlungeRouteImport.update({
  id: '/sensors/plunge',
  path: '/sensors/plunge',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsBundleRoute = SensorsBundleRouteImport.update({
  id: '/sensors/bundle',
  path: '/sensors/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/plunge': typeof PlungeRoute
  '/privacy': typeof PrivacyRoute
  '/sauna': typeof SaunaRoute
  '/shower': typeof ShowerRoute
  '/terms': typeof TermsRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/sensors/bundle': typeof SensorsBundleRoute
  '/sensors/plunge': typeof SensorsPlungeRoute
  '/sensors/sauna': typeof SensorsSaunaRoute
  '/sensors/': typeof SensorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/plunge': typeof PlungeRoute
  '/privacy': typeof PrivacyRoute
  '/sauna': typeof SaunaRoute
  '/shower': typeof ShowerRoute
  '/terms': typeof TermsRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/sensors/bundle': typeof SensorsBundleRoute
  '/sensors/plunge': typeof SensorsPlungeRoute
  '/sensors/sauna': typeof SensorsSaunaRoute
  '/sensors': typeof SensorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/plunge': typeof PlungeRoute
  '/privacy': typeof PrivacyRoute
  '/sauna': typeof SaunaRoute
  '/shower': typeof ShowerRoute
  '/terms': typeof TermsRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/sensors/bundle': typeof SensorsBundleRoute
  '/sensors/plunge': typeof SensorsPlungeRoute
  '/sensors/sauna': typeof SensorsSaunaRoute
  '/sensors/': typeof SensorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/plunge'
    | '/privacy'
    | '/sauna'
    | '/shower'
    | '/terms'
    | '/products/$handle'
    | '/sensors/bundle'
    | '/sensors/plunge'
    | '/sensors/sauna'
    | '/sensors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/plunge'
    | '/privacy'
    | '/sauna'
    | '/shower'
    | '/terms'
    | '/products/$handle'
    | '/sensors/bundle'
    | '/sensors/plunge'
    | '/sensors/sauna'
    | '/sensors'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/dashboard'
    | '/plunge'
    | '/privacy'
    | '/sauna'
    | '/shower'
    | '/terms'
    | '/products/$handle'
    | '/sensors/bundle'
    | '/sensors/plunge'
    | '/sensors/sauna'
    | '/sensors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  PlungeRoute: typeof PlungeRoute
  PrivacyRoute: typeof PrivacyRoute
  SaunaRoute: typeof SaunaRoute
  ShowerRoute: typeof ShowerRoute
  TermsRoute: typeof TermsRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  SensorsBundleRoute: typeof SensorsBundleRoute
  SensorsPlungeRoute: typeof SensorsPlungeRoute
  SensorsSaunaRoute: typeof SensorsSaunaRoute
  SensorsIndexRoute: typeof SensorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shower': {
      id: '/shower'
      path: '/shower'
      fullPath: '/shower'
      preLoaderRoute: typeof ShowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauna': {
      id: '/sauna'
      path: '/sauna'
      fullPath: '/sauna'
      preLoaderRoute: typeof SaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plunge': {
      id: '/plunge'
      path: '/plunge'
      fullPath: '/plunge'
      preLoaderRoute: typeof PlungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/': {
      id: '/sensors/'
      path: '/sensors'
      fullPath: '/sensors/'
      preLoaderRoute: typeof SensorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/sauna': {
      id: '/sensors/sauna'
      path: '/sensors/sauna'
      fullPath: '/sensors/sauna'
      preLoaderRoute: typeof SensorsSaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/plunge': {
      id: '/sensors/plunge'
      path: '/sensors/plunge'
      fullPath: '/sensors/plunge'
      preLoaderRoute: typeof SensorsPlungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/bundle': {
      id: '/sensors/bundle'
      path: '/sensors/bundle'
      fullPath: '/sensors/bundle'
      preLoaderRoute: typeof SensorsBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  PlungeRoute: PlungeRoute,
  PrivacyRoute: PrivacyRoute,
  SaunaRoute: SaunaRoute,
  ShowerRoute: ShowerRoute,
  TermsRoute: TermsRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  SensorsBundleRoute: SensorsBundleRoute,
  SensorsPlungeRoute: SensorsPlungeRoute,
  SensorsSaunaRoute: SensorsSaunaRoute,
  SensorsIndexRoute: SensorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
